### ISSUE TITLE
How to avoid penetration between dexterous hands and objects？

### ISSUE THREAD

**Issue by JackMa-coder** [yzqin/dexpoint-release#2]
Thanks for your wonderful work.
During the execution of the [Dexpoint example](https://github.com/yzqin/dexpoint-release/blob/7b501004c002645e060f6ab4edd93a9dea494165/example/example_dexpoint_grasping.py), I observed a collision issue between the hand and the object during grasping, leading to unrealistic behavior as shown in the figure.
![1696405011182](https://github.com/yzqin/dexpoint-release/assets/54536002/9ee9e530-d72b-41fe-8ae5-e704cca16de7)

The collision settings between the hands and objects are defined in the source program. Could you assist me in resolving this error? 
Thank you for any help！

**Comment by yzqin** [comment]
Hi @JackMa-coder ,

I was wondering that whether it is a RL policy or random action?

This issue might occasionally occur with almost any simulator. Here are a few potential solutions you could consider:
1. Create improved collision meshes of the object with [CoACD](https://github.com/SarahWeiii/CoACD), utilizing more convex shapes to approximate the original visual shape. Bear in mind that this will involve balancing speed and improved contact modeling.
2. Amplify the simulation time-step.
3. Introduce a penalty for excessive contact force, as done in [DexPoint code](https://github.com/yzqin/dexpoint-release/blob/7b501004c002645e060f6ab4edd93a9dea494165/dexpoint/env/rl_env/relocate_env.py#L120) if you are training an RL policy.

**Comment by JackMa-coder** [comment]
As you pointed out, this action was retargeted from a human video demonstration, a procedure analogous to that of your other work, DexMV. Following your advice, I have modified the simulation time-step and hand-object collision was avoided. Currently, my retargeted trajectory only matches the kinematic posture, which results in failure when executing the grasping trajectory in a dynamic simulation environment. Therefore, I would like to determine whether this situation will have a significant impact on the effectiveness of imitation reinforcement learning?

**Comment by JackMa-coder** [comment]
> Hi @JackMa-coder ,
> 
> I was wondering that whether it is a RL policy or random action?
> 
> This issue might occasionally occur with almost any simulator. Here are a few potential solutions you could consider:
> 
>     1. Create improved collision meshes of the object with [CoACD](https://github.com/SarahWeiii/CoACD), utilizing more convex shapes to approximate the original visual shape. Bear in mind that this will involve balancing speed and improved contact modeling.
> 
>     2. Amplify the simulation time-step.
> 
>     3. Introduce a penalty for excessive contact force, as done in [DexPoint code](https://github.com/yzqin/dexpoint-release/blob/7b501004c002645e060f6ab4edd93a9dea494165/dexpoint/env/rl_env/relocate_env.py#L120) if you are training an RL policy.

Thank for your helpful reply. As you pointed out, this action was retargeted from a human video demonstration, a procedure analogous to that of your other work, [DexMV](https://github.com/yzqin/dexmv-sim). Following your advice, I have modified the simulation time-step and hand-object collision was avoided. 

Currently, my retargeted trajectory only matches the kinematic posture, which results in failure when executing the grasping trajectory in a dynamic simulation environment. Therefore, I would like to determine whether this situation will have a significant impact on the effectiveness of imitation reinforcement learning?

**Comment by yzqin** [comment]
Understood. I suspect the penetration might arise from retargeting as it merely matches the kinematic posture. While this may not directly relate to the DexPoint project, I believe that even an imperfect demonstration can prove beneficial in enhancing pure reinforcement learning, based on my understanding.

**Comment by JackMa-coder** [comment]
Thank for your detailed reply.
Best wishes to you.

---Original---
From: "Yuzhe ***@***.***&gt;
Date: Wed, Oct 11, 2023 03:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yzqin/dexpoint-release] How to avoid penetration between dexterous hands and objects？ (Issue #2)




 
Understood. I suspect the penetration might arise from retargeting as it merely matches the kinematic posture. While this may not directly relate to the DexPoint project, I believe that even an imperfect demonstration can prove beneficial in enhancing pure reinforcement learning, based on my understanding.

**Comment by JackMa-coder** [comment]
> Understood. I suspect the penetration might arise from retargeting as it merely matches the kinematic posture. While this may not directly relate to the DexPoint project, I believe that even an imperfect demonstration can prove beneficial in enhancing pure reinforcement learning, based on my understanding.

Thank for your detailed reply.
Best wishes to you.
