### ISSUE TITLE
Request for scenario files or methods for creating them

### ISSUE THREAD

**Issue by JackMa-coder** [yzqin/dexpoint-release#3]
Thank you for your contribution. 
I noticed that the [data file](https://drive.google.com/file/d/1Xe3jgcIUZm_8yaFUsHnO7WJWr8cV41fE/view?usp=sharing)  in the readme are different from the scenarios presented in this article. Could you kindly provide the scenario files or methods for creating them? 
I would appreciate your help. Thank you.

**Comment by yzqin** [comment]
Hi @JackMa-coder ,

I find myself seeking additional clarity on the issue you've brought up. When you refer to the scenarios presented in this article, could you provide further details or a screenshot? The file you've linked here is a ktx file, typically used to establish an environment map and intended solely for visualization.

In the context of DexPoint, it's important to note that this system does not leverage any RGB information. Consequently, the ktx file doesn't have any influence on the algorithm or its performance. It is unrelated to the workings of the DexPoint algorithm.

**Comment by JackMa-coder** [comment]
> Hi @JackMa-coder ,
> 
> I find myself seeking additional clarity on the issue you've brought up. When you refer to the scenarios presented in this article, could you provide further details or a screenshot? The file you've linked here is a ktx file, typically used to establish an environment map and intended solely for visualization.
> 
> In the context of DexPoint, it's important to note that this system does not leverage any RGB information. Consequently, the ktx file doesn't have any influence on the algorithm or its performance. It is unrelated to the workings of the DexPoint algorithm.

Thank you for your answer and sorry for not explaining the situation clearly. I appreciate your clarification on the ktx file and its role in DexPoint.

I am looking for files or methods to create scenarios similar to the room corner scenes in Figure 1 of your DexPoint paper. I am interested in how you generated those scenarios and if you could share the files or methods for creating them. Thank you for your help and contribution.

**Comment by yzqin** [comment]
The room corner scenes are for visualization only and not influence the training or evaluation of the method due to the nature of point cloud RL. Create such scene is very simple, we just place several grey box here (SAPIEN static actor) to make a corner.

**Comment by JackMa-coder** [comment]
Thank you for your prompt and thorough response. 
Now I understand the process and purpose of scene production.
