### ISSUE TITLE
Regarding Loading a custom object and the replication of training code

### ISSUE THREAD

**Issue by anupampatil44** [yzqin/dexpoint-release#4]
Hi @yzqin,
I had a couple of questions I was hoping to get some insight on.

1. Upon inspecting `load_ycb_object()` in `dexpoint-release/dexpoint/utils/ycb_object_utils`, I see that one needs the following files for loading an object:
- `textured_simple.obj`
- `collision.obj`
However, in order to load a new object (like a spoon for example) in the codebase, I am unable to find the corresponding `collision.obj` on the YCB dataset website. Where may I obtain these assets?

2. I was trying to replicate the training of the policy in the codebase but encountered an error in doing so.

Here's a replication of my error:
After cloning the modified codebase [here](https://github.com/anupampatil44/Dexpoint-trainer).
Run the command: `python training_ppo.py`
I get the following error:
![Screenshot from 2023-11-24 16-28-15](https://github.com/yzqin/dexpoint-release/assets/61505546/288dbfae-16dc-4130-a39f-7563d41d41f1)

It would be great if you could kindly give some insight to resolve these issues.

Thanking you in anticipation!

**Comment by yzqin** [comment]
Hello @anupampatil44,

The `textured_simple.obj` file originates from the YCB dataset, while we created the corresponding `collision.obj`, which is the collision mesh of the relevant YCB objects.

You can readily create the collision mesh from the `textured_simple.obj` file by utilizing CoACD. Here's how:

```bash
pip3 install coacd
coacd -i textured_simple.obj -o collision.obj
```

For further details on how to utilize CoACD and optimize the parameters, please visit the original CoACD repository at this link: https://github.com/SarahWeiii/CoACD

**Comment by yzqin** [comment]
For your second question about the error. I think you are using the PPO that is designed for training state RL with the point cloud environment. The solution is pretty simple, for debugging purposes, you can use this PPO code to train an environment without point cloud visualization, like [this one](https://github.com/yzqin/dexpoint-release/blob/main/example/example_use_state_only_env.py)
