### ISSUE TITLE
Is the pre-trained pointnet  used in this paper equal to the one in dexart？

### ISSUE THREAD

**Issue by wslgqq277g** [yzqin/dexpoint-release#5]

**Comment by wslgqq277g** [comment]
Hello yz！
Can u please answer the question in title, thanku!

**Comment by yzqin** [comment]
Hi @wslgqq277g 

There is no pre-trained PointNet in this project. However, the PointNet architecture of DexPoint is the same as the one used in DexArt. The PointNet here is trained from scratch.
